### ISSUE TITLE
Loading image sequence or video file to track

### ISSUE THREAD

**Issue by khodabakhshih** [ocbe-uio/CellMAPtracer#8]
Thanks for sharing your valuable codes. I provide some suggestion and some question.
suggestion:
I suggest you put a demo of your work in GitHub and also give some more explanation on how to use the software.
For example, upload a video or image in GitHub. Then use it in the software and show the results in the demo.
Question:
There is a menu in the software for load image that actually loads a tif image. How to track with a still image? it seems that for tracking  application, a sequence of images or a video file is needed. How can i input my image sequence or video file into software?
Thank you very much and looking forward to hearing from you.
Regards

**Comment by wleoncio** [comment]
Hi @khodabakhshih, thank you for your interest in our software!

For some extra information on using the software, please check out our [Wiki](https://github.com/ocbe-uio/CellMAPtracer/wiki/Supplementary-material) and our [research paper](https://www.mdpi.com/2073-4409/10/2/469/htm).

As for your questions: I could be wrong, but I don't think it is possible to track cells with a still image. The kind of TIF/TIFF files that the software is expecting contains multiple images (like a PDF file with many pages, where each page is one frame). As far as I know, video files are not directly supported, but you could use other software to split such file into multiple images (one per frame), then gather those images into one TIFF file.

Hope this helps!

**Comment by khodabakhshih** [comment]
Thank you very much for your timely and precise response.
